### ISSUE TITLE
여행 기록 프로그램 기능 개선하기

### ISSUE THREAD

**Issue by Cheoroo** [Cheoroo/madcamp24-week1#17]
- [x] : 여행 기록의 날짜 데이터를 달력으로 보여주는 기능 추가
- [ ] : 여행 기록의 지역 탭을 누르면 월별로 travelRecord를 load하는 기능
- [x] : 여행 기록의 초기화면인 지도화면의 View 재구성
- [x] : 여행 기록 create시 사용된 사진이 save되는 시점에 갤러리에 추가되도록 하기
- [x] : 여행기록을 create하는 버튼을 최초로 클릭하면 다이얼로그 화면이 출력되지 않고 바로 사진앱이 실행되는 창이 뜬 후 다이얼로그 창으로 출력하기
- [x] : 여행기록에 연락처 Name을 태깅하는 기능 추가
- [x] : 태깅된 Name을 삭제할수 있는 기능 추가
- [x] : 태깅된 Name을 클릭하면 Contact의 리사이클러뷰를 가져와서 연락처 정보를 가져오는 기능 추가

**Comment by inthelongestday** [comment]
- [ ] 여행 기록 create시 사용된 사진이 save되는 시점에 갤러리에 추가되도록 하기

^ 이거 제가 해보겠습니다!
