### ISSUE TITLE
프로그램 버그 수정

### ISSUE THREAD

**Issue by Cheoroo** [Cheoroo/madcamp24-week1#22]
- [x] : Region 에서 지역 클릭 후 다른탭으로 이동시 다시 Region탭으로 돌아올때 아이템 소멸
- [x] : TravelRecord 생성 후 edit시 기존의 사진의 uri를 불러오지 못함
- [ ] : Region 클릭해서 1의 여행계획을 보다가 다른 탭으로 전환하고 다시 Region에서 클릭해서 2의 여행 계획을 보면 뒤로가기에 1의 여행계획 페이지로 가는 문제 존재(여행 계획 페이지에서는 뒤로가기 한번에 Region페이지로 가야함
- [ ] : 연락처 edit시 첫번째 posiotion의 객체가 수정됨

**Comment by inthelongestday** [comment]
### bug report
기존 여행 기록을 편집할 때,  세부사항을 편집했을 뿐 사진을 변경하지 않아도 save 버튼을 누르면
같은 사진이 중복으로 저장이 된다 (=갤러리 탭에 중복 연동이 된다)
- 저장 시 기존의 GalleryData에 있는 이미지 ID/URI와의 중복 여부를 검사? 비효율적인가?
- 어느 정도 감수 가능한 버그일지도..
